### ISSUE TITLE
customizar color texto/fondo en las plantillas de tipo "detalle"

### ISSUE THREAD

**Issue by damarev** [pmcruzm/Cambridge#6]
Las plantillas de product_h , componentes , serie_exams , serie_exam_c ...   que tienen todas en común la misma estructura, se les va a dar la posibilidad desde el administrador de customizarle un color temático.

Se tendría que aplicar tanto a titulares, enlaces en menús, negritas, colores de fondo...  por ej, en el casi de **product_h** sería un naranja #f17922, y en el caso de **serie_exam_c** sería un rojo #cd0025.

Es decir, que esos colores hay que sacarlos del css (el que esté puesto por defecto en cada caso será a decidir por @e_van )

Resumiendo, que lo que necesitaríamos es que nos pasaras un juego de reglas para aplicar ese color en texto y colores de fondo de toda la plantilla, para quelo pintemos dentro de la plantilla con un _&lt;style&gt;_. Algo así:

``` css
.cont-product h2,
.cont-product h3,
(etc...)
{ color: #CUSTOMCOLOR; }

.block-ver-mas .btn-mas,
(etc...)
{ background-color: #CUSTOMCOLOR; }
```

Lo podrías añadir al _style.css_ como código comentado, y de ahí lo pillamos para pintarlo en la plantilla cuando toque.

Otra posible aproximación, que igual es más sencilla, es que a todo elemento susceptible de ser customizado, le pongas de clase **.theme-color** para los _color_ y **.theme-color-bg** para los _background-color_, así nosotros sólo tendríamos que pintar en la plantilla:

``` css
.theme-color { color: #CUSTOMCOLOR; }
.theme-color-bg { background-color: #CUSTOMCOLOR; }
```

PD: Esto tiene prioridad baja. Si tienes un rato para ir resolviéndolo guay, sino se deja para más adelante.
